import { ResumeData } from '../types/cv';

export const initialEmptyData: ResumeData = {
  receivingEntity: '',
  personalData: {
    firstLastName: '',
    secondLastName: '',
    firstNames: '',
    documentType: 'CC',
    documentNumber: '',
    gender: '',
    nationality: 'COL',
    nationalityCountry: 'COLOMBIA',
    militaryService: {
      bookClass: '',
      number: '',
      militaryDistrict: '',
    },
    birthData: {
      birthDay: '',
      birthMonth: '',
      birthYear: '',
      country: 'COLOMBIA',
      state: '',
      city: '',
    },
    contactAddress: {
      address: '',
      country: 'COLOMBIA',
      state: '',
      city: '',
      phone: '',
      email: '',
    },
  },
  educationData: {
    basic: {
      lastGrade: 11,
      titleObtained: 'BACHILLER ACADÉMICO',
      graduationMonth: '',
      graduationYear: '',
    },
    higher: [
      {
        id: '1',
        degreeType: 'UN',
        approvedSemesters: '10',
        isGraduated: 'SI',
        studyName: '',
        endMonth: '',
        endYear: '',
        professionalCardNumber: '',
      },
    ],
    languages: [
      {
        id: '1',
        language: 'INGLÉS',
        speaks: 'B',
        reads: 'MB',
        writes: 'B',
      },
    ],
  },
  workExperience: [
    {
      id: 'exp-1',
      isCurrent: true,
      companyName: '',
      companyType: '',
      country: '',
      state: '',
      city: '',
      companyEmail: '',
      phoneNumbers: '',
      startDate: { day: '', month: '', year: '' },
      endDate: { day: '', month: '', year: '' },
      jobTitle: '',
      department: '',
      address: '',
    },
  ],
  totalExperience: {
    publicSector: { years: 0, months: 0 },
    privateSector: { years: 0, months: 0 },
    independent: { years: 0, months: 0 },
    manualOverride: false,
  },
  signature: {
    disqualification: 'NO',
    dateAndCity: '',
    signatureType: 'TEXT',
    signatureData: '',
  },
  hrObservations: {
    observations: '',
    dateAndCity: '',
    hrHeadNameAndSignature: '',
  },
};

export const sampleResumeData: ResumeData = {
  receivingEntity: 'MINISTERIO DE TECNOLOGÍAS DE LA INFORMACIÓN Y LAS COMUNICACIONES - MINTIC',
  personalData: {
    firstLastName: 'RODRÍGUEZ',
    secondLastName: 'PÉREZ',
    firstNames: 'JUAN CARLOS',
    documentType: 'CC',
    documentNumber: '1018432985',
    gender: 'M',
    nationality: 'COL',
    nationalityCountry: 'COLOMBIA',
    militaryService: {
      bookClass: '1',
      number: '1018432985',
      militaryDistrict: '05',
    },
    birthData: {
      birthDay: '14',
      birthMonth: '05',
      birthYear: '1990',
      country: 'COLOMBIA',
      state: 'BOGOTÁ D.C.',
      city: 'BOGOTÁ D.C.',
    },
    contactAddress: {
      address: 'CARRERA 7 No. 71 - 21 APTO 502',
      country: 'COLOMBIA',
      state: 'BOGOTÁ D.C.',
      city: 'BOGOTÁ D.C.',
      phone: '3108923411',
      email: 'juancarlos.rodriguez@email.com',
    },
  },
  educationData: {
    basic: {
      lastGrade: 11,
      titleObtained: 'BACHILLER ACADÉMICO',
      graduationMonth: '11',
      graduationYear: '2007',
    },
    higher: [
      {
        id: 'sup-1',
        degreeType: 'UN',
        approvedSemesters: '10',
        isGraduated: 'SI',
        studyName: 'INGENIERÍA DE SISTEMAS Y COMPUTACIÓN',
        endMonth: '06',
        endYear: '2013',
        professionalCardNumber: '25202-148921 CND',
      },
      {
        id: 'sup-2',
        degreeType: 'ES',
        approvedSemesters: '2',
        isGraduated: 'SI',
        studyName: 'GERENCIA DE PROYECTOS INFORMÁTICOS',
        endMonth: '12',
        endYear: '2016',
        professionalCardNumber: '25202-148921 CND',
      },
      {
        id: 'sup-3',
        degreeType: 'MG',
        approvedSemesters: '4',
        isGraduated: 'SI',
        studyName: 'MAESTRÍA EN GOBIERNO DE TECNOLOGÍAS DE LA INFORMACIÓN',
        endMonth: '08',
        endYear: '2021',
        professionalCardNumber: '25202-148921 CND',
      },
    ],
    languages: [
      {
        id: 'lang-1',
        language: 'INGLÉS',
        speaks: 'MB',
        reads: 'MB',
        writes: 'MB',
      },
      {
        id: 'lang-2',
        language: 'FRANCÉS',
        speaks: 'R',
        reads: 'B',
        writes: 'R',
      },
    ],
  },
  workExperience: [
    {
      id: 'exp-1',
      isCurrent: true,
      companyName: 'DEPARTAMENTO ADMINISTRATIVO DE LA FUNCIÓN PÚBLICA',
      companyType: 'PUBLICA',
      country: 'COLOMBIA',
      state: 'BOGOTÁ D.C.',
      city: 'BOGOTÁ D.C.',
      companyEmail: 'contacto@funcionpublica.gov.co',
      phoneNumbers: '6017395656',
      startDate: { day: '15', month: '01', year: '2022' },
      endDate: { day: '', month: '', year: '' },
      jobTitle: 'ASESOR DE TECNOLOGÍA Y TRANSFORMACIÓN DIGITAL',
      department: 'DIRECCIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN',
      address: 'CARRERA 6 No. 12 - 62',
    },
    {
      id: 'exp-2',
      isCurrent: false,
      companyName: 'MINISTERIO DE EDUCACIÓN NACIONAL',
      companyType: 'PUBLICA',
      country: 'COLOMBIA',
      state: 'BOGOTÁ D.C.',
      city: 'BOGOTÁ D.C.',
      companyEmail: 'atencionalciudadano@mineducacion.gov.co',
      phoneNumbers: '6012222800',
      startDate: { day: '01', month: '02', year: '2018' },
      endDate: { day: '31', month: '12', year: '2021' },
      jobTitle: 'PROFESIONAL ESPECIALIZADO DE SISTEMAS',
      department: 'SUBDIRECCIÓN DE DESARROLLO ORGANIZACIONAL',
      address: 'CALLE 43 No. 57 - 14 CAN',
    },
    {
      id: 'exp-3',
      isCurrent: false,
      companyName: 'SOLUCIONES TECNOLÓGICAS DE COLOMBIA S.A.S.',
      companyType: 'PRIVADA',
      country: 'COLOMBIA',
      state: 'BOGOTÁ D.C.',
      city: 'BOGOTÁ D.C.',
      companyEmail: 'rrhh@solucionestec.com.co',
      phoneNumbers: '6017441000',
      startDate: { day: '15', month: '07', year: '2013' },
      endDate: { day: '15', month: '01', year: '2018' },
      jobTitle: 'INGENIERO DE DESARROLLO DE SOFTWARE SENIOR',
      department: 'DEPARTAMENTO DE INGENIERÍA',
      address: 'CALLE 100 No. 19A - 10 OFICINA 401',
    },
  ],
  totalExperience: {
    publicSector: { years: 7, months: 0 },
    privateSector: { years: 4, months: 6 },
    independent: { years: 0, months: 0 },
    manualOverride: false,
  },
  signature: {
    disqualification: 'NO',
    dateAndCity: 'BOGOTÁ D.C., 24 DE JULIO DE 2026',
    signatureType: 'TEXT',
    signatureData: 'Juan Carlos Rodríguez Pérez',
  },
  hrObservations: {
    observations: 'DOCUMENTACIÓN DE SOPORTE VERIFICADA Y COMPLETA EN EXPEDIENTE DIGITAL.',
    dateAndCity: 'BOGOTÁ D.C., 24 DE JULIO DE 2026',
    hrHeadNameAndSignature: 'MARÍA FERNANDA GÓMEZ - JEFA DE TALENTO HUMANO',
  },
};
